name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Bump version and push tag
      uses: devibadampudi/My-project@main
      env:
        GITHUB_TOKEN: ${{ secrets.TAG_TOKEN }}
        REPO_OWNER: devibadampudi
